const store = [
  {
    order: 1,
    hierarchy: 'Seraphim',
    fullName: 'VEHUIAH',
    definitionOfName: 'God exalted and exalted above all things',
    godName: 'JEHOVAH',
    description: 'N/A',
    regenceMonth: 'March',
    regenceDays: '21-25',
    regenceHours: 'N/A',
    colors: 'purple',
    scent: 'Electre',
    gender: 'Femal',
    invocation: 'Make your powers take root in me. Amen',
    exhortation: 'The time.',
    callFormula: 'But you, o VEHUIAH, You are my honor and hold my head high',
    psalms: 'Ps3:4',
    category: 'health',
  },
  {
    order: 6,
    hierarchy: 'Seraphim',
    fullName: 'LELAHEL',
    definitionOfName: 'Praiseworthy god',
    godName: 'ABGED',
    description: 'N/A',
    regenceMonth: 'April',
    regenceDays: '15-20',
    regenceHours: 'N/A',
    colors: 'purple',
    scent: 'Santal',
    gender: 'Male',
    invocation: 'Lelahel! I give you thanks, Lord, for this stopover,  Amen!',
    exhortation: 'I gave you powers to create, so that eternal truths ',
    callFormula: 'Celebrate the Lord who sits in Zion; proclaim among the peoples his deeds',
    psalms: 'Ps9:12',
    category: 'Love',
  },
];

export default store;
